version: '3.3'

volumes:
  pg_data:
  static:

services:
  # Postgres container
  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  # Django backend container
  backend:
    image: alexeyzaliznuak/auto_docs_online_backend
    env_file: ../.env
    volumes:
      - static:/app/backend_static
    depends_on:
      - db

  # Frontend container
  frontend:
    image: maxiq/auto_docs_online_frontend
    volumes:
      - static:/app/result_build/build

  # Gateway container
  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - static:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
